{{- /*
PodDisruptionBudget is a way to limit the number of concurrent disruptions that your application experiences,
allowing for higher availability while permitting the cluster administrator to manage the clusters nodes.

Resource Spec Reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#poddisruptionbudget-v1beta1-policy

*/ -}}

{{- /*
`minAvailable` and `maxUnavailable` can be either an absolute number of pods (integer) or a percentage of total pods (string)
See here: https://kubernetes.io/docs/tasks/run-application/configure-pdb/#rounding-logic-when-specifying-percentages

If podDisruptionBudget.minAvailable is a percentage pass it as is, else check if it is greater or equal of autoscaling.minReplicas
*/ -}}

{{- define "pdbMinAvailableValidate" -}}
  {{- $hpaMin := .Values.autoscaling.minReplicas | toString -}}
  {{- $pdbMin := .Values.podDisruptionBudget.minAvailable | toString -}}
  {{- if contains "%" $pdbMin -}}
    {{- printf "\"%v\"" $pdbMin -}}
  {{- else -}}
    {{- if (gt (atoi $hpaMin) (atoi $pdbMin)) -}}
      {{- printf "%v" $pdbMin }}
    {{- else -}}
      {{- fail (printf "PodDisruptionBudget minAvaible cant be equal or greater than HPA minReplicas. Current values: pdb %v hpa %v" $pdbMin $hpaMin) }}
    {{- end -}}
  {{- end -}}
{{- end -}}

{{- if and (.Values.podDisruptionBudget.enabled) (.Values.autoscaling.enabled) -}}
{{- if or (ne .Values.podDisruptionBudget.minAvailable "") (ne .Values.podDisruptionBudget.maxUnavailable "") }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
{{ template "lib-metadata.metadata" . }}
  name: {{ template "lib-metadata.fullname" . }}
spec:
  minAvailable: {{ include "pdbMinAvailableValidate" . }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
{{- end }}
{{- end }}
