global:
  nameOverride: "gfechio"
  fullnameOverride: "gfechio-server"
  labels:
    component: ""
    partOf: ""
    owner: "platform"
  service:
    port: 8080
app:
  replicaCount: 1
  image:
    registry: registry.private.k8s.management.thebeat.co/beat/
    name: gfechio-server
    tag: TOB-2552
    pullPolicy: Always
  esIndexName: "gfechio-owner"
  changeCause: "gfechio-cause"
  command:
    cmd: []
    extraArgs: []
  service:
    type: ClusterIP
    ports:
      - port: 80
        targetPort: 5000
        protocol: ""
        name: "http"
  env: {}
  ingresses:
    api:
      enabled: true
      type: private
      annotations: {}
      path: /
      host: gfechio
      clusterSuffix: private.k8s.stress.thebeat.co
  resources: {}
  monitoring:
    enabled: false
    path: /metrics
    port: 8081
  tracing:
    enabled: false
    env:
      P8ATRON_JAEGER_SAMPLER_TYPE: probabilistic
      PATRON_JAEGER_SAMPLER_PARAM: 0
      PATRON_JAEGER_AGENT_HOST: $(NODE_IP)
      PATRON_JAEGER_AGENT_PORT: 6831
  blackboxProbe:
    enabled: false
    path: /healthz
    for: 5m
    severity: warning
  livenessProbe:
    httpGet:
      path: /healthz
      port: 5000
  readinessProbe:
    httpGet:
      path: /healthz
      port: 5000
  autoscaling:
    enabled: true
    minReplicas: "2"
    maxReplicas: "10"
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
  podDisruptionBudget:
    enabled: false
    minAvailable: "1"
    maxUnavailable: ""
  secrets:
    enabled: false
    mountPath: /mnt/beat/secrets/
    items: {}
    files: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  iamRole:
    enabled: false
    name: "role-name"
  mop:
    enabled: false
    annotation: "master-of-puppets.alpha.kubernetes.io/enabled"
istio:
  publicExposed: enable
  istioGateway: "ingressgateway"
  auth:
    enabled: true
    allowNamespace:
    - dmv
    - rest
    forwardOriginalJWT: false
    identityProvider: https://dex.k8s.stress.thebeat.co
    protectedHosts:
    - gfechio-server.gfechio.svc
    policy:
    - group: [Devops]
      methods: ["*"]
      paths: [/*]
    - group: [Backend]
      methods: ["*"]
      paths: [/*]
