{{- if .Values.secrets.enabled -}}
{{- $files := .Files }}
apiVersion: v1
kind: Secret
metadata:
{{ template "lib-metadata.metadata" $ }}
  name: {{ template "lib-metadata.fullname" $ }}
data: 
{{- range $key, $value := .Values.secrets.items }}
  {{$key | quote }}: |-
    {{ $value | b64enc }}
{{- end -}}

{{- range $key, $fname := .Values.secrets.files}}
  {{$key | quote }}: |-
    {{ $files.Get $fname | b64enc }}
{{- end -}}
{{end}}
