apiVersion: v1
kind: Service
{{ template "lib-metadata.metadata" . }}
  name: {{ template "lib-metadata.fullname" . }}
  annotations: {{ if and (not .Values.blackboxProbe.enabled) (not .Values.mop.enabled) -}}{}{{- end }}
    {{ if .Values.blackboxProbe.enabled -}}
    prometheus.io/probe: "true"
    prometheus.io/probe_path: {{ .Values.blackboxProbe.path }}
    prometheus.io/probe_for: {{ .Values.blackboxProbe.for }}
    prometheus.io/probe_severity: {{ .Values.blackboxProbe.severity }}
    {{- end }}
    {{ if .Values.mop.enabled -}}
    {{ .Values.mop.annotation }}: "true"
    {{- end }}
spec:
  {{- with  .Values.service }}
  type: {{ .type }}
  ports:
    {{- range .ports }}
    - port: {{ .port | default "80" }}
      targetPort: {{ .targetPort | default .port }}
      protocol: "TCP"
      name: {{ .name | default (printf "%s-%d" (.protocol | default "HTTP" | lower) (int64 .port)) }}
    {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "lib-metadata.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
